/**
 * ==============================================================================
 * Nestora — Production-Safe Admin Seeding Script
 * ==============================================================================
 * Guarantees:
 * 1. Never seeds default or hardcoded credentials in production or staging.
 * 2. Requires explicit environment credentials or generates a secure 24-character
 *    one-time password printed to the console for the deployment operator.
 * 3. Rejects known insecure/default passwords (e.g. Admin@123, password, 123456).
 * 4. Checks if an admin user already exists and safely aborts if so.
 *
 * Usage:
 *   ADMIN_USERNAME=ops_admin ADMIN_EMAIL=ops@nestora.com ADMIN_PASSWORD=StrongPass@2026 npm run seed:admin
 * ==============================================================================
 */

require("dotenv").config();
const crypto = require("crypto");
const mongoose = require("mongoose");
const User = require("../models/User");
const connectDB = require("../utils/db");

const INSECURE_PASSWORDS = [
  "admin",
  "admin@123",
  "admin123",
  "password",
  "password123",
  "123456",
  "qwerty",
  "default_secret",
];

async function seedAdmin() {
  console.log("\n===============================================================");
  console.log("🔒 NESTORA PRODUCTION-SAFE ADMIN SEEDING PROCESS");
  console.log("===============================================================\n");

  await connectDB();

  const isProduction = process.env.NODE_ENV === "production";
  const isStaging = process.env.NODE_ENV === "staging";

  // Check if any admin account already exists
  const existingAdmin = await User.findOne({ role: "admin" });
  if (existingAdmin) {
    console.log(`ℹ️  Admin account already exists: "${existingAdmin.username}" (${existingAdmin.email}).`);
    console.log("   No modifications made. Seeding aborted safely.\n");
    await mongoose.connection.close();
    return;
  }

  // Determine admin credentials
  const username = (
    process.env.ADMIN_USERNAME ||
    process.env.SEED_ADMIN_USERNAME ||
    (isProduction ? "" : "nestora_admin")
  ).trim();

  const email = (
    process.env.ADMIN_EMAIL ||
    process.env.SEED_ADMIN_EMAIL ||
    (isProduction ? "" : "admin@nestora.com")
  ).trim().toLowerCase();

  let password = (
    process.env.ADMIN_PASSWORD ||
    process.env.SEED_ADMIN_PASSWORD ||
    ""
  ).trim();

  let isAutoGenerated = false;

  if (isProduction && (!username || !email)) {
    console.error("❌ ERROR: Production admin seeding requires ADMIN_USERNAME and ADMIN_EMAIL environment variables.");
    await mongoose.connection.close();
    process.exit(1);
  }

  // If password was supplied, ensure it is not a known weak default
  if (password) {
    if (INSECURE_PASSWORDS.includes(password.toLowerCase()) || password.length < 8) {
      console.error("❌ ERROR: Provided ADMIN_PASSWORD is too weak or uses a forbidden default password.");
      await mongoose.connection.close();
      process.exit(1);
    }
  } else {
    // Generate a high-entropy 24-character one-time password
    password = `Nestora!${crypto.randomBytes(12).toString("hex")}`;
    isAutoGenerated = true;
  }

  // Check if the username or email is already taken by a non-admin
  const existingUser = await User.findOne({
    $or: [{ username }, { email }],
  });

  if (existingUser) {
    existingUser.role = "admin";
    existingUser.isVerified = true;
    if (password) {
      existingUser.password = password;
    }
    await existingUser.save();

    console.log(`✅ Promoted existing user "${existingUser.username}" (${existingUser.email}) to Admin.`);
    if (isAutoGenerated) {
      console.log("\n---------------------------------------------------------------");
      console.log("🔑 ONE-TIME GENERATED ADMIN CREDENTIALS (SAVE IMMEDIATELY):");
      console.log(`   Username: ${existingUser.username}`);
      console.log(`   Email:    ${existingUser.email}`);
      console.log(`   Password: ${password}`);
      console.log("---------------------------------------------------------------\n");
    }
    await mongoose.connection.close();
    return;
  }

  // Create fresh Admin user
  const adminUser = new User({
    username,
    email,
    password,
    role: "admin",
    isVerified: true,
  });

  await adminUser.save();

  console.log("✅ Admin user seeded successfully with verified status.");
  console.log("\n---------------------------------------------------------------");
  console.log("🔑 ADMIN CREDENTIALS:");
  console.log(`   Username: ${username}`);
  console.log(`   Email:    ${email}`);
  if (isAutoGenerated) {
    console.log(`   Password: ${password}  <-- ONE-TIME SECURE GENERATED KEY`);
  } else {
    console.log("   Password: [SET VIA ENVIRONMENT VARIABLE]");
  }
  console.log("---------------------------------------------------------------\n");

  await mongoose.connection.close();
}

if (require.main === module) {
  seedAdmin().catch(async (err) => {
    console.error("Failed to seed admin user:", err.message);
    try {
      if (mongoose.connection.readyState !== 0) {
        await mongoose.connection.close();
      }
    } catch (e) {
      /* ignore */
    }
    process.exit(1);
  });
}

module.exports = seedAdmin;
